/**
 * Tupaia
 * Copyright (c) 2017 - 2021 Beyond Essential Systems Pty Ltd
 */

export const ENTITIES = [
  { code: 'redblue', name: 'Pokemon Red/Blue', type: 'project' },
  { code: 'goldsilver', name: 'Pokemon Gold/Silver', type: 'project' },

  { code: 'KANTO', name: 'Kanto', type: 'country' },
  { code: 'PALLET', name: 'Pallet Town', type: 'village' },
  { code: 'VIRIDIAN', name: 'Viridian City', type: 'city' },
  { code: 'PEWTER', name: 'Pewter City', type: 'city' },
  { code: 'CERULEAN', name: 'Cerulean City', type: 'city' },
  { code: 'CERULEAN_CAVE', name: 'Cerulean Cave', type: 'facility' },
  { code: 'VERMILLION', name: 'Vermillion City', type: 'city' },
  { code: 'LAVENDER', name: 'Lavender Town', type: 'village' },
  { code: 'PKMNTOWER', name: 'Pokemon Tower', type: 'facility' },
  { code: 'LAVENDERRADIOTOWER', name: 'Lavender Radio Tower', type: 'facility' },
  { code: 'CELADON', name: 'Celadon City', type: 'city' },
  { code: 'CELADONGAME', name: 'Celadon Game Corner', type: 'facility' },
  { code: 'FUCHSIA', name: 'Fuchsia City', type: 'city' },
  { code: 'SAFARI', name: 'Safari Zone', type: 'facility' },
  { code: 'SAFFRON', name: 'Saffron City', type: 'city' },
  { code: 'SILPH', name: 'Silph Co.', type: 'facility' },
  { code: 'CINNABAR', name: 'Cinnabar Island', type: 'village' },
  { code: 'PKMNMANSION', name: 'Pokemon Mansion', type: 'facility' },

  { code: 'JOHTO', name: 'Johto', type: 'country' },
  { code: 'NEWBARK', name: 'New Bark Town', type: 'village' },
  { code: 'CHERRYGROVE', name: 'Cherrygrove City', type: 'city' },
  { code: 'VIOLET', name: 'Violet City', type: 'city' },
  { code: 'SPROUTTOWER', name: 'Sprout Tower', type: 'facility' },
  { code: 'AZALEA', name: 'Azalea Town', type: 'village' },
  { code: 'SLOWPOKEWELL', name: 'Slowpoke Well', type: 'facility' },
  { code: 'GOLDENROD', name: 'Goldenrod City', type: 'city' },
  { code: 'ECRUTEAK', name: 'Ecruteak City', type: 'city' },
  { code: 'BELLTOWER', name: 'Bell Tower', type: 'facility' },
  { code: 'BURNEDTOWER', name: 'Burned Tower', type: 'facility' },
  { code: 'OLIVINE', name: 'Olivine City', type: 'city' },
  { code: 'OLIVINELIGHTHOUSE', name: 'Olivine Lighthouse', type: 'facility' },
  { code: 'CIANWOOD', name: 'Cianwood City', type: 'city' },
  { code: 'MAHOGANY', name: 'Mahogany Town', type: 'village' },
  { code: 'BLACKTHORN', name: 'Blackthorn City', type: 'city' },
  { code: 'DRAGONDEN', name: "Dragon's Den", type: 'facility' },

  { code: 'PKMNLEAGUE', name: 'Pokemon League', type: 'district' },
];

export const ENTITY_RELATIONS = [
  { parent: 'redblue', child: 'KANTO', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'PALLET', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'VIRIDIAN', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'PEWTER', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'CERULEAN', hierarchy: 'redblue' },
  { parent: 'CERULEAN', child: 'CERULEAN_CAVE', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'VERMILLION', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'LAVENDER', hierarchy: 'redblue' },
  { parent: 'LAVENDER', child: 'PKMNTOWER', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'CELADON', hierarchy: 'redblue' },
  { parent: 'CELADON', child: 'CELADONGAME', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'FUCHSIA', hierarchy: 'redblue' },
  { parent: 'FUCHSIA', child: 'SAFARI', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'SAFFRON', hierarchy: 'redblue' },
  { parent: 'SAFFRON', child: 'SILPH', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'CINNABAR', hierarchy: 'redblue' },
  { parent: 'CINNABAR', child: 'PKMNMANSION', hierarchy: 'redblue' },
  { parent: 'KANTO', child: 'PKMNLEAGUE', hierarchy: 'redblue' },

  { parent: 'KANTO', child: 'KANTO', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'PALLET', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'VIRIDIAN', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'PEWTER', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'CERULEAN', hierarchy: 'goldsilver' },
  { parent: 'CERULEAN', child: 'CERULEAN_CAVE', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'VERMILLION', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'LAVENDER', hierarchy: 'goldsilver' },
  { parent: 'LAVENDER', child: 'LAVENDERRADIOTOWER', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'CELADON', hierarchy: 'goldsilver' },
  { parent: 'CELADON', child: 'CELADONGAME', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'FUCHSIA', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'SAFFRON', hierarchy: 'goldsilver' },
  { parent: 'KANTO', child: 'SILPH', hierarchy: 'goldsilver' },
  { parent: 'goldsilver', child: 'JOHTO', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'NEWBARK', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'CHERRYGROVE', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'VIOLET', hierarchy: 'goldsilver' },
  { parent: 'VIOLET', child: 'SPROUTTOWER', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'AZALEA', hierarchy: 'goldsilver' },
  { parent: 'AZALEA', child: 'SLOWPOKEWELL', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'GOLDENROD', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'ECRUTEAK', hierarchy: 'goldsilver' },
  { parent: 'ECRUTEAK', child: 'BELLTOWER', hierarchy: 'goldsilver' },
  { parent: 'ECRUTEAK', child: 'BURNEDTOWER', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'OLIVINE', hierarchy: 'goldsilver' },
  { parent: 'OLIVINE', child: 'OLIVINELIGHTHOUSE', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'CIANWOOD', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'MAHOGANY', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'BLACKTHORN', hierarchy: 'goldsilver' },
  { parent: 'BLACKTHORN', child: 'DRAGONDEN', hierarchy: 'goldsilver' },
  { parent: 'JOHTO', child: 'PKMNLEAGUE', hierarchy: 'goldsilver' },
];
