/**
 * Tupaia MediTrak
 * Copyright (c) 2017 Beyond Essential Systems Pty Ltd
 */

export const LATEST_SERVER_SYNC_TIMESTAMP = 'LATEST_SERVER_SYNC_TIMESTAMP';
export const CURRENT_USER_EMAIL = 'LOGGED_IN_USER_EMAIL_ADDRESS';
export const PERMISSION_GROUPS_IN_DATABASE = 'PERMISSION_GROUPS_IN_DATABASE';
export const COUNTRIES_IN_DATABASE = 'COUNTRIES_IN_DATABASE';
